### ISSUE TITLE
Fix Non Packaged Migrations in Laravel 5.6

### ISSUE THREAD

**Issue by nwogu** [nwogu/bagpack#4]

**Comment by terry-lonesski** [comment]
thanks

**Comment by nwogu** [comment]
@terry-lonesski please try again. let me know if it works now.

**Comment by terry-lonesski** [comment]
@nwogu great! works great! :+1: 
But it works only if you set table name as string like `Schema::create('table', ....)`
When table name is based on variable, nothing happens
For example, I have migration for package [anlutro/laravel-settings](https://github.com/anlutro/laravel-settings)
```
Schema::create($this->tablename, function(Blueprint $table)
		{
			$table->increments('id');
			$table->string($this->keyColumn)->index();
			$table->text($this->valueColumn);
		});
```
And your packege can't recognize table name in this case
But anyway, I :heart: your package anyway

**Comment by nwogu** [comment]
thanks, @terry-lonesski. Glad I could help. 
I still haven't figured out how to handle edge cases based on variable names.
I'll continuously update if I've got any ideas.
